### ISSUE TITLE
Data links are wrong

### ISSUE THREAD

**Issue by A-Abedi** [BruceW91/CVSE#11]
Hello. 
I am trying to download the data needed for training the model using the links you've mentioned:

> wget https://scanproject.blob.core.windows.net/scan-data/data.zip
> wget https://scanproject.blob.core.windows.net/scan-data/vocab.zip

But these links seem to be wrong, or maybe they have expired. Where can I download these data?

Is there any pre-trained model available for MSCOCO and Flickr30k datasets to download?

Thanks.

**Comment by BruceW91** [comment]
Hi, I have updated the links to download data:

> wget https://iudata.blob.core.windows.net/scan/data.zip
> wget https://iudata.blob.core.windows.net/scan/vocab.zip

 And you can see more details from this project https://github.com/kuanghuei/SCAN.

**Comment by A-Abedi** [comment]
Thank you very much.

Is there any pre-trained model available for MSCCOCO and FLickr30k to download?
I have limitations in the resources and, on top of that, in time.
I wanted to know if pre-trained models are available to download, I use them.

Thank you.

**Comment by BruceW91** [comment]
Do you mean the off-the-shelf trained model on both datasets? Actually, they have existed in the following directories:

>  MSCOCO: CVSE/runs/coco/CVSE_COCO/model_best.pth.tar
>  Flickr30k: CVSE/runs/f30k/CVSE_f30k/model_best.pth.tar

**Comment by A-Abedi** [comment]
Thank you so much.
