### ISSUE TITLE
The code for generating the 'coco_adj_concepts.pkl' file.

### ISSUE THREAD

**Issue by sqiangcao99** [BruceW91/CVSE#13]
Thank you for generously sharing your work. This is very inspiring. The ‘coco_adj_concepts.pkl’ contains a dict (keys['nums', 'adj_O_P', 'adj_O_M', 'adj_all']) which is used by the function 'gen_A_concept'. I checked SCAN, which seems to be no related code provided. Could you please bring out more details？

**Comment by BruceW91** [comment]
Hi, the four keys in the dict means:

- 'nums' -> the occurence times of all concepts of the textual captions over the dataset

- 'adj_O_P' -> the statistical co-occurence between object concepts and Propoerty concepts of the textual captions over the dataset

- 'adj_O_M' -> the statistical co-occurence between object concepts and Motion concepts of the textual captions over the dataset

- 'adj_all' -> the statistical co-occurence between all concepts of the textual captions over the dataset
