### ISSUE TITLE
About the expriment on MS COCO 5 folds 1K set

### ISSUE THREAD

**Issue by liuyyy111** [BruceW91/CVSE#15]
I think the code of test on MS COCO 1k test should be:

`python evaluate.py --data_path "$DATA_PATH" --data_name 'coco_precomp' --model_path './runs/coco/CVSE_COCO/model_best.pth.tar' --data_name_vocab coco_precomp --split testall --fold5  
`
but the results on MS COCO in Table.1 in your paper are not tested on 5 folds 1k test，is it a bug?

**Comment by BruceW91** [comment]
Hi, we have updated our latest version of our paper on Arxiv (https://arxiv.org/pdf/2007.08883.pdf). We have re-implemented the experiments and please refer to the new version.

**Comment by haoopan** [comment]
还有这种操作？原论文的数据有问题重新写篇论文就完事了？
