### ISSUE TITLE
The code for generating the 'coco_adj_concepts.pkl' file

### ISSUE THREAD

**Issue by gzwo-O** [BruceW91/CVSE#16]
Thank you for providing us the code of your excellent work and I was wondering if you could provide me with the code that generated the 'coco_adj_concepts. pkl' file that counts the frequency of Object and Property occurrences.

**Comment by Nishant3815** [comment]
Hi @BruceW91 , 

Thanks for sharing this excellent work. Can you please share us the code that helped in creating concept and counting it. Also, @gzwo-O, in case you figured this out, it would be really helpful if you can help me with the same. 

Thanks 
Nishant

**Comment by gzwo-O** [comment]
I've been a little busy recently, I'll reply to you as soon as I have time, because I haven't done this project for a long time




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BruceW91/CVSE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月7日(星期二) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BruceW91/CVSE] The code for generating the 'coco_adj_concepts.pkl' file (#16)





 
Hi @BruceW91 ,
 
Thanks for sharing this excellent work. Can you please share us the code that helped in creating concept and counting it. Also, @gzwo-O, in case you figured this out, it would be really helpful if you can help me with the same.
 
Thanks
 Nishant

**Comment by Nishant3815** [comment]
@gzwo-O Thanks a ton, would wait for your reply.

**Comment by gzwo-O** [comment]
Hello, According to the 13 papers cited in the paper, I found a specific method, you can refer to it.
`
import nltk
import numpy as np
import json
import pickle
import collections
import os
# nltk.download('averaged_perceptron_tagger')
# nltk.download('punkt')
root = '/data2/gaozhenwei/hgr_data/TGIF/annotation/RET/int2word.npy'  # 
name_file = '/data2/gaozhenwei/hgr_data/TGIF/public_split/trn_names.npy'
ref_caption_file = '/data2/gaozhenwei/hgr_data/TGIF/annotation/RET/ref_captions.json'
result_path = '/data2/gaozhenwei/hgr_data/TGIF/annotation/RET/cipin.json'
POS_path = '/data2/gaozhenwei/hgr_data/TGIF/annotation/RET/pos.json'
caption_file = '/data2/gaozhenwei/hgr_data/TGIF/public_split/caption.npy'
adj_file = '/data2/gaozhenwei/hgr_data/TGIF/annotation/RET/adj_file.pkl'
int2word = np.load(root)  
tags = nltk.pos_tag(int2word)
with open(POS_path, 'w', encoding='utf-8') as f:
    json.dump(tags, f)
names = np.load(name_file)
captions = set()
ref_captions = json.load(open(ref_caption_file))
for i, name in enumerate(names):
    for j, sent in enumerate(ref_captions[name]):
        captions.add(sent)
captions = list(captions)
np.save(caption_file, captions)

words = []

for caption in captions:
    words.append(nltk.word_tokenize(caption))
counter = collections.Counter([tk for st in words for tk in st])  
counter = dict(filter(lambda x: x[1] >= 5, counter.items()))
counter = sorted(counter.items(), key=lambda x: x[1], reverse=True)
with open(result_path, 'w', encoding='utf-8') as f:
    json.dump(counter, f)

print('Hello world!!!')

O_word, M_word, P_word = [], [], []
o_num, m_num, p_num = [], [], []
Object, Motion, Property = ['NN', 'NNS'], ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ'], ['CD', 'JJ', 'JJR', 'RB']
# with open(result_path, 'r') as f:
#     counter = json.load(f)
# with open(POS_path, 'r') as f:
#     tags = json.load(f)

POS = {}
for word, pos in tags:
    POS[word] = pos

for word, num in counter:
    if len(o_num) > 270 and len(m_num) > 60 and len(p_num) > 30:
        break
    if POS[word] in Object:
        O_word.append(word)
        o_num.append(num)
    elif POS[word] in Motion:
        M_word.append(word)
        m_num.append(num)
    elif POS[word] in Property:
        P_word.append(word)
        p_num.append(num)

O_word, M_word, P_word = O_word[: 210], M_word[: 60], P_word[: 30]
o_num, m_num, p_num = o_num[: 210], m_num[: 60], p_num[: 30]
all_word = O_word + M_word + P_word
all_num = o_num + m_num + p_num
adj_O_P, adj_O_M, adj_all = np.zeros((300, 300)), np.zeros((300, 300)), np.zeros((300, 300))
for i, i_word in enumerate(all_word):
    for j, j_word in enumerate(all_word):
        if i >= j:
            continue
        cnt = 0
        for sent in words:
            if i_word in sent and j_word in sent:
                cnt += 1
        adj_all[i, j] = cnt
        adj_all[j, i] = cnt


adj_O_M[: 270, : 270] = adj_all[: 270, : 270]
adj_O_P[: 210, : 210] = adj_all[: 210, : 210]
adj_O_P[: 210, 270:] = adj_all[: 210, 270:]
adj_O_P[270:, :210] = adj_all[270:, :210]
adj = {}
adj['nums'] = np.array(all_num)
adj['adj_O_P'] = np.array(adj_O_P)
adj['adj_O_M'] = np.array(adj_O_M)
adj['adj_all'] = np.array(adj_all)

with open(adj_file, 'wb') as f:
    pickle.dump(adj, f, pickle.HIGHEST_PROTOCOL)
`
paper: [https://openaccess.thecvf.com/content_ICCV_2019/papers/Hou_Joint_Syntax_Representation_Learning_and_Visual_Cue_Translation_for_Video_ICCV_2019_paper.pdf]

**Comment by gzwo-O** [comment]
Hello, According to the 13 papers cited in the paper, I found a specific method, you can refer to it,
in file.zip , I will support code and data, But please note that the data is TGIF (a video dataset) not the dataset used in CVSE, the dataset we provide is just to give you a better understanding of how the code works in order to apply this method to your own dataset. I hope I can help you, feel free to ask any questions.
paper: [Joint Syntax Representation Learning and Visual Cue Translation
for Video Captioning](https://openaccess.thecvf.com/content_ICCV_2019/papers/Hou_Joint_Syntax_Representation_Learning_and_Visual_Cue_Translation_for_Video_ICCV_2019_paper.pdf)
[file.zip](https://github.com/BruceW91/CVSE/files/8885777/file.zip)

**Comment by gzwo-O** [comment]
> 

Here are code

**Comment by Nishant3815** [comment]
Thanks a ton. I was able to recreate the files.
