### ISSUE TITLE
data download problem

### ISSUE THREAD

**Issue by PamelaDDD** [BruceW91/CVSE#19]
Hello scholar, the link to the dataset is broken. Could you provide other ways to download the data?

**Comment by BruceW91** [comment]
Download link of Flickr30k dataset: https://pan.baidu.com/s/1r0RVUwctJsI0iNuVXHQ6kA#list/path=%2Fsharelink1300395039-553456144438794%2Fflickr%2030k&parentPath=%2Fsharelink1300395039-553456144438794, Extraction code: hrf3
Download link of MSCOCO-2014 dataset: https://cocodataset.org/#download
