### ISSUE TITLE
what the concept correlation matrix 'adj_O_P', 'adj_O_M' and 'adj_all' refer to respectively?

### ISSUE THREAD

**Issue by ahagary** [BruceW91/CVSE#3]
hello, wang, can you tell me the distinction of  the concept correlation matrix  `adj_O_P`, `adj_O_M` and `adj_all` in your code? Thank you very much.

**Comment by BruceW91** [comment]
Hi, the *adj_O_P* refers to the co-occurence frequency between Object-and--Property conepts, *adj_O_M* refers to the co-occurence frequency between Object-and--Motion conepts, and *adj_all* refers to the co-occurence frequency between all concepts. In our paper, we only use the *adj_all* annotations.

**Comment by ahagary** [comment]
> Hi, the _adj_O_P_ refers to the co-occurence frequency between Object-and--Property conepts, _adj_O_M_ refers to the co-occurence frequency between Object-and--Motion conepts, and _adj_all_ refers to the co-occurence frequency between all concepts. In our paper, we only use the _adj_all_ annotations.

Got it. Thank you!
