### ISSUE TITLE
About Graph Convolution

### ISSUE THREAD

**Issue by Liujin21** [BruceW91/CVSE#5]
Hello author, first of all thank you for your open source code. I have a question about the graph convolution part. I saw that in your paper, each layer of graph convolution must be followed by an activation function, but the second layer of the code you gave Graph convolution does not add activation function. I want to know why? Can I add it?

**Comment by BruceW91** [comment]
Hi, I followed the [Thomas Kipf](https://arxiv.org/abs/1609.02907) to use the standard graph convolution in my implementation besides its softmax function. We feel sorry that it's not rigorous to define the graph convolution in our paper (the definition of  graph convolution on last layer should be a exception). You can also try to add the activation function on the last layer and I haven't tried it.

**Comment by Liujin21** [comment]
Thank you so much for taking the time to reply to me.
