### ISSUE TITLE
Question about corrected score

### ISSUE THREAD

**Issue by vincentlux** [BruceW91/CVSE#6]
Thanks for the wonderful work and the code release! I notice that the final score for MSCOCO and Flickr30k has been updated in this repo. May I ask if it's possible to also update the number in the CVSE paper in arXiv? Thanks!

**Comment by BruceW91** [comment]
Hi, we are contacting the PC chairs of ECCV2020 and we will also update the number in the CVSE paper in arXiv in the future.

**Comment by vincentlux** [comment]
Got it, thanks!
