### ISSUE TITLE
About Concept Correlation Graph Building

### ISSUE THREAD

**Issue by Liujin21** [BruceW91/CVSE#7]
Hello, I would like to ask whether the object of the confidence scale (CS) function is P or E? , Because I saw the cited paper "Multi-Label Image Recognition with Graph Convolutional Networks" that the binary correlation matrix is obtained from the conditional probability matrix P, while the binary correlation matrix in your paper is obtained from the smoothed matrix E.

**Comment by BruceW91** [comment]
Hi, we actually employ the conditional probability matrix **P** as the object of the confidence scale (CS) function. We feel sorry that the Eq.(2) in paper is a typo, and the matrix **E** in Eq.(2) should be matrix  **P**.
